server:
  port: 8080

mybatis:
  mapperLocations: classpath*:com.huawei.hicloud.dao
  typeAliasesPackage: com.huawei.hicloud.pojo,com.huawei.hicloud.vo

spring:
  datasource: 
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: hicloud
    password: root
  redis:
    host: localhost
    port: 6379
    # Redis数据库索引（默认为0）
    database: 0
#    password: 
    timeout: 0
    pool: 
      max-active: 8
      # 负数表示没有限制
      max-wait: -1
      max-idle: 8
      min-idle: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#    publisher-confirms: true
#    virtual-host: /
    


  